name: Regal
on: pull_request
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Regal
<<<<<<< HEAD
        uses: StyraInc/setup-regal@v0.2.0
        with:
          version: v0.11.0
      - run: regal lint --format=github cvat/apps/iam/rules
=======
        uses: StyraInc/setup-regal@v1
        with:
          version: v0.21.3
      - run: regal lint --format=github cvat/apps/*/rules
>>>>>>> cvat/develop
